# Generated by Django 2.1.2 on 2019-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('esal', models.FloatField(max_length=10)),
                ('eaddr', models.CharField(max_length=40)),
                ('emob', models.IntegerField()),
            ],
        ),
    ]
