# Generated by Django 2.1.2 on 2019-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20191211_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
