# Generated by Django 2.1.2 on 2019-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20191212_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
